
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/goblin/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.17.6-arch1-1 - x86_64
...
